### ISSUE TITLE
ReferenceGenerator itself becomes a dependency of NuPkg

### ISSUE THREAD

**Issue by AArnott** [onovotny/ReferenceGenerator#10]
The `NuSpec.ReferenceGenerator` package's own nuspec lacks this tag:

```
<developmentDependency>true</developmentDependency>
```

As a result, installing it into a class library causes it to appear as a dependency that NuProj then adds to the .nuspec file during the build.

**Comment by clairernovotny** [comment]
Good catch, I wasn't totally aware of that nuspec option but it makes sense. Any chance of a PR? Otherwise it might not be till Monday.

**Comment by AArnott** [comment]
Done.

**Comment by clairernovotny** [comment]
Fixed in 1.3.4, now on Nuget.org. Thanks!
