### ISSUE TITLE
Version number parsing for non-English region settings

### ISSUE THREAD

**Issue by andijakl** [onovotny/ReferenceGenerator#14]
As we just discovered at the MVP Summit, the parsing of the .net version number doesn't work if the computer's number format region is set to German locales. It will not recognize the "4.5" as the corresponding number, as it'd expect to read "4,5" instead. As a result, the tool things the library doesn't meet the requirements.

As solution, specify the neutral / English format provider for the Double.TryParse method.

**Comment by clairernovotny** [comment]
Fixed in 1.3.6 just pushed to NuGet.org
