### ISSUE TITLE
Provide examples of how to invoke the command line tool

### ISSUE THREAD

**Issue by rchom** [onovotny/ReferenceGenerator#25]
The documentation on how to pass arguments/parameters to the command line tool is unclear.  Please add some examples.

**Comment by ravensorb** [comment]
+1 

when I try I am getting some odd errors like "RG001: Image is too small."

**Comment by clairernovotny** [comment]
Hi,

Sorry for the delay -- at this point, this tool should no longer be used as the current guidance is to reference `NETStandard.Library` instead. Thus, there's no need for this tool.

I'll get an update to the readme up.
