### ISSUE TITLE
Add empty groups for PCL profiles in "Packages containing  netstandard  and existing libraries" section?

### ISSUE THREAD

**Issue by feO2x** [onovotny/ReferenceGenerator#26]
Just a small question: in the ["Packages containing  netstandard  and existing libraries"](https://github.com/onovotny/ReferenceGenerator#packages-containing-netstandard-and-existing-libraries) section of readme.md, you list target framework groups like e.g. net45 or win8 that use packages.config to manage NuGet dependencies. Wouldn't it be useful to add empty groups for PCL profiles to this list, too? By default, PCL projects created with VS2015 use packages.config unless you upgrade them to target .NET Standard 1.x - this way the packages.config file is updated when you install a PCL targeting .NET Standard 1.x via NuGet.

Maybe we should adjust or add a paragraph reflecting this issue.

**Comment by clairernovotny** [comment]
All of the guidance here is negated by the current recommendations for netstandard.

For that, you should use `netstandard.library 1.6.0` as your dependency and not create granular dependency groups or blank ones. No need anymore.

**Comment by feO2x** [comment]
Ok, I probably have missed these recommendations. Thanks!
