### ISSUE TITLE
Error RG001 on UWP library using PackageReference instead of project.json

### ISSUE THREAD

**Issue by bramborman** [onovotny/ReferenceGenerator#29]
I'm getting this error since I "upgraded" my UWP library to the new NuGet reference type.

    EXEC : error RG001: Only PCLs are supported by this tool. TargetFrameworkProfile or TargetFrameworkVersion is missing

<sub>
(By upgrading I mean creating new project and copying all the files etc to the new project while checking the changes in git diff.)
</sub>

**Comment by clairernovotny** [comment]
You shouldn't need this tool anymore.... it was for a time last year before using netstandard.library was the recommended approach.

**Comment by bramborman** [comment]
So I could just remove reference to this tool and delete all dependencies in my `.nuspec` file? Or the netstandard.library NuGet will generate them for me instead of this tool?

**Comment by clairernovotny** [comment]
You can remove the reference to this tool. As to the specifics of what you need, it depends on your library. Do you have an example?

**Comment by bramborman** [comment]
Yes, it's UWPHelper and [here][1] you can see the dependencies generated by your tool the last time.

[1]: https://github.com/bramborman/UWPHelper/blob/dev/UWPHelper.nuspec

**Comment by clairernovotny** [comment]
For that, I would just use the direct dependencies that you have as `PackageReference`, including "Microsoft.NETCore.UniversalWindowsPlatform". Be warned though, that 5.3.x will only work with VS 2017 and higher. If you want your library to be usable in VS 2015, you need to use 5.2.x.

**Comment by bramborman** [comment]
OK, thanks. Is there any article about that?

**Comment by clairernovotny** [comment]
About which part?

**Comment by bramborman** [comment]
You said that it's now recommended to use netstandard.library. So something where this recommendation is.

**Comment by clairernovotny** [comment]
@terrajobst, where is your explanation on this?

**Comment by terrajobst** [comment]
I answered in the .NET Standard FAQ: https://github.com/dotnet/standard/blob/master/docs/faq.md#should-i-reference-the-meta-package-or-should-i-reference-individual-packages
