### ISSUE TITLE
Illegal characters in path when building on Appveyor

### ISSUE THREAD

**Issue by darrelmiller** [onovotny/ReferenceGenerator#6]
Compiling locally works fine, but when AppVeyor picked up the changes and tried to build it failed with the following error:

```
EXEC : error RG001: Illegal characters in path. [C:\projects\uritemplates\src\UriTemplatesPCL\UriTemplatesPCL.csproj]
C:\projects\uritemplates\packages\NuSpec.ReferenceGenerator.1.3.1\build\portable-net45+win+wpa81+wp80+MonoAndroid10+xamarinios10+MonoTouch10\NuSpec.ReferenceGenerator.targets(42,5): error MSB3073: 
The command ""C:\projects\uritemplates\packages\NuSpec.ReferenceGenerator.1.3.1\build\portable-net45+win+wpa81+wp80+MonoAndroid10+xamarinios10+MonoTouch10\..\..\tools\RefGen.exe" ".NETPortable,Version=v4.5,Profile=Profile259;" dotnet "*Undefined***\Tavis.UriTemplates.nuspec" 
```

This might be caused by the fact that my .nuspec file isn't in the solution folder so I have provided an explicit path to the nuspec file using a property in the csproj file.

```
<NuSpecFile>..\..\build\Tavis.UriTemplates.nuspec</NuSpecFile>
```

**Comment by clairernovotny** [comment]
The file parameters need to be fully qualified...

Can you try the following:
`<NuSpecFile>$(MSBuildThisFileDirectory)..\..\build\Tavis.UriTemplates.nuspec</NuSpecFile>`

**Comment by clairernovotny** [comment]
Any updates on this? Please reopen if this is still an issue.
